#!/bin/sh

#ROOT_PATH=/ProxWarnDev/
ROOT_PATH=/mnt/share/ProxWarnDev/install/
PYGPS_PATH=lib/gpsd-3.5/
DPKT_PATH=lib/dpkt/
PCAP_PATH=lib/pcap/
WIFI2UDP_PATH=drivers/wifi-to-udp/
UDP2WIFI_PATH=drivers/udp-to-wifi/
GPS2UDP2_PATH=drivers/gpsd-to-udp/
UDP2DB_PATH=database/writers/
CORE_PATH=core/
UDP2LED_PATH=drivers/udp-to-led/
ADSB_PATH=drivers/adsb-to-udp/
UDP2PDA_PATH=drivers/udp-to-pda/
GMAP_PATH=lib/googlemap/

DISKDEV=/dev/sda1
LABEL=dosfslabel

PROG=start.py

PYTHONPATH=$ROOT_PATH$PYGPS_PATH:$ROOT_PATH$WIFI2UDP_PATH
PYTHONPATH=$PYTHONPATH:$ROOT_PATH$UDP2WIFI_PATH:$ROOT_PATH$GPS2UDP2_PATH
PYTHONPATH=$PYTHONPATH:$ROOT_PATH$UDP2DB_PATH:$ROOT_PATH$CORE_PATH
PYTHONPATH=$PYTHONPATH:$ROOT_PATH$UDP2LED_PATH:$ROOT_PATH$DPKT_PATH
PYTHONPATH=$PYTHONPATH:$ROOT_PATH$ADSB_PATH:$ROOT_PATH$UDP2PDA_PATH
export PYTHONPATH=$PYTHONPATH:$ROOT_PATH$PCAP_PATH:$ROOT_PATH$GMAP_PATH

if [ -b $DISKDEV ]; then

  ID=`$LABEL $DISKDEV`
  python $ROOT_PATH/$CORE_PATH/$PROG $ID
fi